window.SAMPLE_DATA = {
  portfolioKpis: [
    ["Programas", "6", "Activos", "▦"],
    ["GAPs Estratégicos", "X", "Prioritarios", "⚠"],
    ["Demanda Activa", "XXX", "Iniciativas", "↗"],
    ["Evolución target", "X%", "Avance global", "◎"],
    ["Países", "X", "Alcance", "◎"],
  ],
  programs: [
    {
      id: "blue",
      name: "Blue",
      description: "Solución Agentic para cliente",
      status: "En Curso",
      functional: 50,
      systems: 50,
      architecture: 50,
      enabled: false,
      icon: "🤖",
    },
    {
      id: "orchestration",
      name: "Orchestration",
      description: "Asistencia y Orquestación",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "✣",
    },
    {
      id: "futura",
      name: "Futura & Inno",
      description: "Innovación en canales digitales",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "🚀",
    },
    {
      id: "smart-comms",
      name: "Smart Comms",
      description: "Comunicaciones",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "💬",
    },
    {
      id: "aixbanker",
      name: "AIxBanker",
      description: "Asistente para gestores",
      status: "En Curso",
      functional: 50,
      systems: 60,
      architecture: 50,
      enabled: true,
      icon: "🧠",
    },
    {
      id: "aixrcp",
      name: "AIxRCP",
      description: "Próximos",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "…",
    },
  ],
  modules: [
    {
      id: "backlog",
      title: "Backlog estratégico",
      description: "Demanda, gaps e iniciativas priorizadas.",
      route: null,
      status: "Próximamente",
    },
    {
      id: "functional",
      title: "Mapa de capacidades funcionales",
      description: "Dominios, capacidades y funcionalidades.",
      route: "functional",
      status: "Activo",
    },
    {
      id: "systems",
      title: "Mapa de sistemas",
      description: "Capas, componentes e inventario AS IS.",
      route: "systems",
      status: "Activo",
    },
    {
      id: "architecture",
      title: "Arquitectura de referencia",
      description: "Arquitectura target y principios.",
      route: null,
      status: "Próximamente",
    },
  ],
  roles: [
    ["PA", "Product Architect"],
    ["SA", "Solution Architect"],
    ["SeP", "Security Partner"],
    ["PTL", "Platform Tech Lead"],
    ["PBO", "Product Business Owner"],
  ],
  priorities: [
    "Panorama Buddy",
    "Competencia",
    "BBVA Assistant",
    "Streaming voz",
    "Proyecto Scout",
  ],
  functional: [
    {
      domain: "Interacción con el gestor",
      capability: "Asistente conversacional",
      features: [
        "Q&A contextual",
        "Resumen cliente",
        "Sugerencias comerciales",
      ],
    },
    {
      domain: "Bases de conocimiento",
      capability: "Conocimiento interno",
      features: ["Políticas", "Procedimientos", "Catálogo productos"],
    },
    {
      domain: "Productividad del gestor",
      capability: "Automatización tareas",
      features: ["Preparación reunión", "Minutas", "Seguimiento acciones"],
    },
    {
      domain: "Gestión comercial y ventas",
      capability: "Next best action",
      features: ["Oportunidades", "Recomendaciones", "Alertas comerciales"],
    },
    {
      domain: "Operaciones y procesos",
      capability: "Soporte operativo",
      features: ["Consulta estado", "Guía procesos", "Escalado"],
    },
    {
      domain: "Nuevo dominio",
      capability: "Capacidades futuras",
      features: ["Por definir", "Discovery", "Experimentación"],
    },
  ],
  systems: [
    {
      layer: "Canales",
      component: "Salesforce / CRM UI",
      description: "Interfaz de trabajo del gestor",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "Conversa",
      component: "Conversa Platform",
      description: "Orquestación conversacional",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "GenAI",
      component: "GenAI Framework",
      description: "Servicios de IA generativa",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "LLM Providers",
      component: "Model Providers",
      description: "Proveedores LLM corporativos",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "Fuentes de Datos",
      component: "Customer Data",
      description: "Contexto y datos de cliente",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "Otros Servicios",
      component: "Observability",
      description: "Trazabilidad, métricas y analítica",
      status: "AS IS",
      country: "Global",
    },
  ],
  projects: [
    {
      programId: "aixbanker",
      country: "ES",
      product: "blue-buddy",
      id: "bb-desktop-sscc",
      name: "Escritorio SSCC",
      summary: "Evolución del escritorio operativo para soporte comercial.",
      description:
        "Iniciativa para consolidar funcionalidades críticas del escritorio y mejorar la experiencia de gestión.",
      status: "at-risk",
      progress: 62,
      owner: "Equipo Producto",
      nextMilestoneTitle: "Validación funcional",
      nextMilestoneDate: "2026-04-15",
      lastUpdate: "2026-03-20",
      strategicGoal: "Reducir fricción operativa y acelerar la atención.",
      businessValue:
        "Mejora de eficiencia, trazabilidad y calidad del servicio.",
      mainRisks: "Dependencias con integración y disponibilidad de negocio.",
      dependencies:
        "APIs internas, datos de cliente y validación de arquitectura.",
    },
    {
      programId: "aixbanker",
      country: "ES",
      product: "blue-buddy",
      id: "bb-genai-supervisor",
      name: "Supervisor GenAI",
      summary: "Orquestación y control de asistentes GenAI.",
      description:
        "Construcción del supervisor para coordinar asistentes, trazabilidad y gobierno.",
      status: "on-track",
      progress: 45,
      owner: "Arquitectura",
      nextMilestoneTitle: "PoC técnica",
      nextMilestoneDate: "2026-05-10",
      lastUpdate: "2026-03-22",
      strategicGoal: "Crear una capa común de orquestación GenAI.",
      businessValue: "Reutilización, control y escalabilidad.",
      mainRisks: "Madurez técnica, dependencias de plataforma y seguridad.",
      dependencies: "SKY, Knowledge Assistant, Sales Assistant.",
    },
  ],

  projectPhases: [
    {
      projectId: "bb-desktop-sscc",
      order: 1,
      phaseName: "Análisis funcional",
      progress: 100,
      status: "done",
      startDate: "2026-01-10",
      targetDate: "2026-02-15",
      comments: "Fase completada con alcance validado.",
    },
    {
      projectId: "bb-desktop-sscc",
      order: 2,
      phaseName: "Construcción",
      progress: 65,
      status: "at-risk",
      startDate: "2026-02-16",
      targetDate: "2026-04-15",
      comments: "Riesgo por dependencias técnicas.",
    },
    {
      projectId: "bb-genai-supervisor",
      order: 1,
      phaseName: "Diseño de arquitectura",
      progress: 70,
      status: "on-track",
      startDate: "2026-02-01",
      targetDate: "2026-04-01",
      comments: "Diseño en validación.",
    },
    {
      projectId: "bb-genai-supervisor",
      order: 2,
      phaseName: "PoC",
      progress: 20,
      status: "planned",
      startDate: "2026-04-02",
      targetDate: "2026-05-10",
      comments: "Pendiente de entornos.",
    },
  ],
};
